import { DirectionProvider } from "@/components/ui/direction";
import FloatingSocials from "@/features/shared/components/floating-socials";
import Footer from "@/features/shared/components/footer";
import Navbar from "@/features/shared/components/navbar";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { Cairo, Geist } from "next/font/google";
import { notFound } from "next/navigation";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cairo = Cairo({
  subsets: ["arabic"],
  variable: "--font-cairo",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    return notFound();
  }
  setRequestLocale(locale);
  const messages = await getMessages();

  const font = locale === "ar" ? cairo : geistSans;

  return (
    <html lang={locale} className={`${font.className} `} suppressHydrationWarning>
      <body dir={locale === "ar" ? "rtl" : "ltr"}>
        <NextIntlClientProvider messages={messages}>
          <DirectionProvider dir={locale === "ar" ? "rtl" : "ltr"}>
            <Navbar/>
            {children}
            <Footer />
            <FloatingSocials />
            <Toaster richColors position="top-right"/>
          </DirectionProvider>
        </NextIntlClientProvider>

      </body>
    </html>
  );
}
